Repository ossca-2025/pr-agent-mentoring, pull requests merged in 2025-05, with the labels that each got.

#63 docs: 2주차 5조 주소미 과제
  weekly/week-2/group-5/joosomi.md
  weekly/week-2/group-5/joosomi_img.png
Labels: Review effort 2/5

#64 docs: 2주차 1조 김예지 과제
  weekly/group-1/김예지.md
Labels: Review effort 2/5

#65 docs: 2주차 3조 서강문 과제
  weekly/week-2/group-3/images/kangmoonseo-image-1.jpg
  weekly/week-2/group-3/images/kangmoonseo-image-2.jpg
  weekly/week-2/group-3/서강문.md
Labels: Review effort 2/5

#75 docs: 2주차 4조 박영신 과제 보완
  weekly/week-2/group-4/박영신.md
Labels: Review effort 2/5

#73 이예찬 1주차 과제
  weekly/week-1/group-2/이예찬.md
Labels: Review effort 1/5

#71 docs: 2주차 5조 채윤희 과제 (재정리)
  weekly/week-2/group-5/chaeyunhui.md
  weekly/week-2/group-5/chaeyunhui_mcp2.png
Labels: Review effort 2/5

#66 docs: 2주차 4조 김범진 과제
  weekly/week-2/group-4/김범진.md
Labels: Review effort 2/5

#68 docs: 2주차 2조 원종인 과제
  weekly/week-2/group-2/원종인.md
Labels: Review effort 1/5

#67 docs: 2주차 5조 이재민 과제
  weekly/week-2/group-5/docs: 2주차 5조 이재민 과제
Labels: Review effort 1/5

#81 docs: 3주차 1조 조별과제 제출
  group/group-1.md
  weekly/week-3/group-1/README.md
  weekly/week-3/group-1/configurations/ci-cd-and-deployment.md
  weekly/week-3/group-1/configurations/etc.md
  weekly/week-3/group-1/configurations/features-and-actions.md
  weekly/week-3/group-1/configurations/model-config.md
  weekly/week-3/group-1/configurations/pr-management.md
  weekly/week-3/group-1/configurations/version-control.md
Labels: Review effort 2/5

#77 docs: 3주차 2조 조별과제 제출
  weekly/week-3/group-2/group-2.md
Labels: Review effort 2/5

#79 docs: 3주차 3조 조별과제 제출
  weekly/week-3/group-3/README.md
  weekly/week-3/group-3/assignment.md
Labels: Review effort 1/5

#80 docs: 3주차 4조 조별과제 제출
  group/group-4.md
  weekly/week-3/group-4/group-4.md
Labels: Review effort 4/5

#78 docs: 3주차 5조 조별과제 제출
  group/group-5.md
  weekly/week-3/group-5/assignment.md
  weekly/week-3/group-5/images/image 1.png
  weekly/week-3/group-5/images/image 10.png
  weekly/week-3/group-5/images/image 11.png
  weekly/week-3/group-5/images/image 12.png
  weekly/week-3/group-5/images/image 13.png
  weekly/week-3/group-5/images/image 14.png
  weekly/week-3/group-5/images/image 15.png
  weekly/week-3/group-5/images/image 16.png
  weekly/week-3/group-5/images/image 17.png
  weekly/week-3/group-5/images/image 18.png
  weekly/week-3/group-5/images/image 19.png
  weekly/week-3/group-5/images/image 2.png
  weekly/week-3/group-5/images/image 20.png
  weekly/week-3/group-5/images/image 21.png
  weekly/week-3/group-5/images/image 22.png
  weekly/week-3/group-5/images/image 23.png
  weekly/week-3/group-5/images/image 24.png
  weekly/week-3/group-5/images/image 25.png
  weekly/week-3/group-5/images/image 26.png
  weekly/week-3/group-5/images/image 27.png
  weekly/week-3/group-5/images/image 28.png
  weekly/week-3/group-5/images/image 29.png
  weekly/week-3/group-5/images/image 3.png
  weekly/week-3/group-5/images/image 30.png
  weekly/week-3/group-5/images/image 31.png
  weekly/week-3/group-5/images/image 32.png
  weekly/week-3/group-5/images/image 33.png
  weekly/week-3/group-5/images/image 34.png
  weekly/week-3/group-5/images/image 35.png
  weekly/week-3/group-5/images/image 36.png
  weekly/week-3/group-5/images/image 37.png
  weekly/week-3/group-5/images/image 4.png
  weekly/week-3/group-5/images/image 5.png
  weekly/week-3/group-5/images/image 6.png
  weekly/week-3/group-5/images/image 7.png
  weekly/week-3/group-5/images/image 8.png
  weekly/week-3/group-5/images/image 9.png
  weekly/week-3/group-5/images/image.png
Labels: Review effort 1/5

#82 docs: 4주차 1조 조별과제 제출
  group/group-1.md
  weekly/week-4/group-1/Ideation/llm_reasoning_effort.md
  weekly/week-4/group-1/Ideation/local_provider.md
  weekly/week-4/group-1/Ideation/sequence_diagram.md
  weekly/week-4/group-1/README.md
Labels: Review effort 2/5

#85 docs: 4주차 3조 조별과제 제출
  weekly/week-4/group-3/assingment.md
  weekly/week-4/group-3/images/1587_improve_gogo.png
  weekly/week-4/group-3/images/1587_improve_nono.png
  weekly/week-4/group-3/images/PEP_8.jpg
  weekly/week-4/group-3/images/calc_calude_tokens.jpg
  weekly/week-4/group-3/images/docs_merged_fast.jpg
  weekly/week-4/group-3/images/github_provider_publish_lables.jpg
  weekly/week-4/group-3/images/gitlab_provider_publish_labels.jpg
  weekly/week-4/group-3/images/god_metno.jpg
  weekly/week-4/group-3/images/how_to_contri.png
  weekly/week-4/group-3/images/load_large_diff.jpg
  weekly/week-4/group-3/images/mrt_merged.jpg
Labels: Review effort 2/5

#83 docs: 4주차 5조 조별과제 제출
  group/group-5.md
  weekly/week-4/group-5/assignment.md
Labels: Review effort 2/5

#88 2조 4주차 과제 업로드
  weekly/week-4/group-2/assignment.md
  weekly/week-4/group-2/images/image 1.png
  weekly/week-4/group-2/images/image 2.png
  weekly/week-4/group-2/images/image.png
Labels: Review effort 2/5

#91 docs: 2조 5주차 조별 과제
  weekly/week-5/group-2/assignment.md
Labels: Review effort 1/5

#90 5조 5주차 조별 과제
  weekly/week-5/group-5/assignment.md
Labels: Review effort 2/5

#97 docs: 6주차 5조 과제 제출
  weekly/week-6/group-5/assignment.md
Labels: Review effort 2/5
